/* eslint-disable */
module.exports = {
  one: {
    raw: {
      title: '',
      file: 'test.js',
      ctx: {},
      suites: [ {
        title: 'Mochawesome Suite',
        ctx: {},
        suites: [],
        tests: [ {
          title: 'passing test',
          body: 'function () {}',
          async: 0,
          sync: true,
          _timeout: 2000,
          _slow: 75,
          _enableTimeouts: true,
          timedOut: false,
          _trace: {},
          _retries: -1,
          _currentRetry: 0,
          pending: false,
          type: 'test',
          parent: '[Circular ~.suites.0]',
          ctx: {},
          uuid: 'e061e2eb-e4aa-49e4-b6f3-41bbb23752a9',
          _events: {},
          _eventsCount: 1,
          duration: 0,
          state: 'passed',
          speed: 'fast'
        } ],
        pending: false,
        _beforeEach: [],
        _beforeAll: [],
        _afterEach: [],
        _afterAll: [],
        root: false,
        _timeout: 2000,
        _enableTimeouts: true,
        _slow: 75,
        _bail: false,
        _retries: -1,
        _onlyTests: [],
        _onlySuites: [],
        delayed: false,
        parent: '[Circular ~]'
      } ],
      tests: [],
      pending: false,
      _beforeEach: [],
      _beforeAll: [],
      _afterEach: [],
      _afterAll: [],
      root: true,
      _timeout: 2000,
      _enableTimeouts: true,
      _slow: 75,
      _bail: false,
      _retries: -1,
      _onlyTests: [],
      _onlySuites: [],
      delayed: false
    },
    cleaned: {
      title: '',
      suites: [ {
        title: 'Mochawesome Suite',
        ctx: {},
        suites: [],
        tests: [ {
          title: 'passing test',
          body: 'function () {}',
          async: 0,
          sync: true,
          timedOut: false,
          pending: false,
          type: 'test',
          parent: '[Circular ~.suites.0]',
          ctx: {},
          uuid: 'e061e2eb-e4aa-49e4-b6f3-41bbb23752a9',
          duration: 0,
          state: 'passed',
          speed: 'fast',
          _currentRetry: 0,
          _enableTimeouts: true,
          _events: {},
          _eventsCount: 1,
          _retries: -1,
          _slow: 75,
          _timeout: 2000,
          _trace: {}
        } ],
        pending: false,
        _beforeEach: [],
        _beforeAll: [],
        _afterEach: [],
        _afterAll: [],
        root: false,
        _timeout: 2000,
        _enableTimeouts: true,
        _slow: 75,
        _bail: false,
        _retries: -1,
        _onlyTests: [],
        _onlySuites: [],
        delayed: false,
        parent: '[Circular ~]'
      } ],
      tests: [],
      failedHooks: [],
      pending: [],
      root: true,
      _timeout: 2000,
      uuid: 'fc3f8bee-4feb-4f28-8e27-a680704c9176',
      fullFile: 'test.js',
      file: 'test.js',
      passes: [],
      failures: [],
      skipped: [],
      hasTests: false,
      hasFailedHooks: false,
      hasSuites: true,
      totalTests: 0,
      totalPasses: 0,
      totalFailures: 0,
      totalPending: 0,
      totalSkipped: 0,
      hasPasses: false,
      hasFailures: false,
      hasPending: false,
      hasSkipped: false,
      duration: 0,
      rootEmpty: true
    }
  },
  two: {
    raw: {
      title: 'Mochawesome Suite',
      ctx: {},
      suites: [],
      tests: [ {
        title: 'passing test',
        body: 'function () {}',
        async: 0,
        sync: true,
        _timeout: 2000,
        _slow: 75,
        _enableTimeouts: true,
        timedOut: false,
        _trace: {},
        _retries: -1,
        _currentRetry: 0,
        pending: false,
        type: 'test',
        parent: '[Circular ~]',
        ctx: {},
        uuid: 'e061e2eb-e4aa-49e4-b6f3-41bbb23752a9',
        _events: {},
        _eventsCount: 1,
        duration: 0,
        state: 'passed',
        speed: 'fast'
      } ],
      pending: false,
      _beforeEach: [],
      _beforeAll: [
        {
        title:  "\"before all\" hook",
        body: "() => {\n            throw new Error();\n        }",
        async: 0,
        sync: true,
        _timeout: 2000,
        _slow: 75,
        _enableTimeouts: true,
        timedOut: false,
        _trace: {},
        _retries: -1,
        _currentRetry: 0,
        pending: false,
        type: "hook",
        parent: "[Circular ~]",
        ctx: {
          _runnable: "[Circular ~._beforeAll.0]",
          test: "[Circular ~._beforeAll.0]"
        },
        uuid: 'e061e1eb-e9aa-49e4-b6f3-41bbb27752a8',
        _events: {},
        _eventsCount: 1,
        duration: 0,
        _error: null,
        state: "failed",
        err: {}
    }
      ],
      _afterEach: [],
      _afterAll: [],
      root: false,
      _timeout: 2000,
      _enableTimeouts: true,
      _slow: 75,
      _bail: false,
      _retries: -1,
      _onlyTests: [],
      _onlySuites: [],
      delayed: false,
      parent: {
        title: '',
        suites: [ '[Circular ~]' ],
        tests: [],
        pending: [],
        root: true,
        _timeout: 2000,
        uuid: '6bb1320f-e964-4c1d-93e7-c40b2e73e225',
        fullFile: '',
        file: '',
        passes: [],
        failures: [],
        skipped: [],
        hasTests: false,
        hasSuites: true,
        totalTests: 0,
        totalPasses: 0,
        totalFailures: 0,
        totalPending: 0,
        totalSkipped: 0,
        hasPasses: false,
        hasFailures: false,
        hasPending: false,
        hasSkipped: false,
        duration: 0,
        rootEmpty: true
      }
    },
    cleaned: {
      title: 'Mochawesome Suite',
      suites: [],
      tests: [ {
        title: 'passing test',
        fullTitle: 'passing test',
        timedOut: false,
        duration: 0,
        state: 'passed',
        speed: 'fast',
        pass: true,
        fail: false,
        pending: false,
        context: undefined,
        code: '',
        err: {},
        isRoot: undefined,
        uuid: 'e061e2eb-e4aa-49e4-b6f3-41bbb23752a9',
        parentUUID: undefined,
        skipped: false,
        isHook: false
      } ],
      failedHooks: [
        {
        title: "\"before all\" hook",
        fullTitle: "\"before all\" hook",
        timedOut: false,
        duration: 0,
        state: "failed",
        pass: false,
        fail: true,
        pending: false,
        context: undefined,
        code: "throw new Error();",
        err: {},
        isRoot: undefined,
        uuid: "e061e1eb-e9aa-49e4-b6f3-41bbb27752a8",
        parentUUID: undefined,
        skipped: false,
        speed: undefined,
        isHook: true
      }
      ],
      pending: [],
      root: false,
      rootEmpty: false,
      _timeout: 2000,
      uuid: 'fc3f8bee-4feb-4f28-8e27-a680704c9176',
      fullFile: '',
      file: '',
      passes: [ {
        title: 'passing test',
        fullTitle: 'passing test',
        timedOut: false,
        duration: 0,
        state: 'passed',
        speed: 'fast',
        pass: true,
        fail: false,
        pending: false,
        context: undefined,
        code: '',
        err: {},
        isRoot: undefined,
        uuid: 'e061e2eb-e4aa-49e4-b6f3-41bbb23752a9',
        parentUUID: undefined,
        skipped: false,
        isHook: false
      } ],
      failures: [],
      skipped: [],
      hasTests: true,
      hasFailedHooks: true,
      hasSuites: false,
      totalTests: 1,
      totalPasses: 1,
      totalFailures: 0,
      totalPending: 0,
      totalSkipped: 0,
      hasPasses: true,
      hasFailures: false,
      hasPending: false,
      hasSkipped: false,
      duration: 0,
    }
  }
};
