<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mochawesome Report Card</title>
    <link rel="stylesheet" href="css/mochawesome.css">
  </head>
  <body>
    <!-- NAVBAR -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <h1 class="report-title">{{reportTitle}}</h1>
        <h3 class="report-date">{{dateFormat stats.end 'dddd, MMMM D YYYY, hh:mma'}}</h3>
      </div>
    </div>

    <!-- Report Summary -->
    <div class="summary">
      <div class="container">
        {{#stats}}
          {{> _summary}}
        {{/stats}}
      </div>
    </div>
    <div class="statusbar">
      <div class="container">
        {{#stats}}
          {{> _statusbar}}
        {{/stats}}
      </div>
    </div>

    <!-- Suites -->
    <div class="details container">
      {{#suites}}
        {{> _suite}}
      {{/suites}}
    </div>

    <footer>
      <div class="container">
        <p class="small">Report generated by <a href="https://github.dowjones.net/grubera/mochawesome" target="_blank">mochawesome</a>.<br>Designed and built by <a href="http://twitter.com/talknmime" target="_blank">@talknmime</a> at <a href="http://github.com/dowjones" target="_blank">Dow Jones</a>. &copy;2014.</p>
      </div>
    </footer>

    <!-- Scripts -->
    <script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="js/mochawesome.js"></script>
    <!--<script>
      window.onload = onLoadFunction;
      function onLoadFunction() {
        makeSuiteCharts();
      }
      function makeSuiteCharts() {
        var chartOpts = {
          percentageInnerCutout : 70,
          animationEasing: 'easeOutQuint',
          showTooltips: false
        };
        var suiteCharts = document.getElementsByClassName("suite-chart");
        for (var i=0; i<suiteCharts.length; i++) {
          var ctx = suiteCharts[i].getContext('2d');
          var data = [{
            value: suiteCharts[i].getAttribute('data-total-passes')*10,
            color:"#5cb85c",
            highlight: "#FF5A5E",
            label: "Passed"
          },
          {
            value: suiteCharts[i].getAttribute('data-total-failures')*10,
            color: "#d9534f",
            highlight: "#FFC870",
            label: "Failed"
          },
          {
            value: suiteCharts[i].getAttribute('data-total-pending')*10,
            color: "#999999",
            highlight: "#FFC870",
            label: "Pending"
          }]
          new Chart(ctx).Doughnut(data, chartOpts);
        };
      }
      </script>-->
  </body>
</html>
